"""Initial migration

Revision ID: 5ee972155655
Revises: 
Create Date: 2025-09-18 16:57:00.818397

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '5ee972155655'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turbines',
    sa.Column('turbine_id', sa.UUID(), nullable=False),
    sa.Column('farm_name', sa.String(length=100), nullable=False),
    sa.Column('unit_id', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('owner_company', sa.String(length=100), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('turbine_id'),
    sa.UniqueConstraint('farm_name', 'unit_id', name='uq_farm_unit')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'READER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('expert_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('turbine_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('status_tag', sa.Enum('NORMAL', 'WATCH', 'ALARM', 'MAINTENANCE', 'UNKNOWN', name='statustag'), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=False),
    sa.Column('log_status', sa.Enum('DRAFT', 'PUBLISHED', name='logstatus'), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_tags', sa.JSON(), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('ai_review_status', sa.Enum('UNREVIEWED', 'APPROVED', 'REJECTED', name='aireviewstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['turbine_id'], ['turbines.turbine_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('attachments',
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('ai_excerpt', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['expert_logs.log_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('log_chunks',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('turbine_id', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('status_tag', sa.String(length=20), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['expert_logs.log_id'], ),
    sa.ForeignKeyConstraint(['turbine_id'], ['turbines.turbine_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_chunks')
    op.drop_table('attachments')
    op.drop_table('expert_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('turbines')
    # ### end Alembic commands ###