"""add_turbine_status_field

Revision ID: 97ba1b9d601b
Revises: 5ee972155655
Create Date: 2025-09-19 10:46:03.674791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ba1b9d601b'
down_revision = '5ee972155655'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turbines', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turbines', 'status')
    # ### end Alembic commands ###