"""add_detail_field_to_timeline_events

Revision ID: def456789012
Revises: abc123456789
Create Date: 2025-01-25 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def456789012'
down_revision = 'abc123456789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline_events', sa.Column('detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeline_events', 'detail')
    # ### end Alembic commands ###